version: "3.9"
services:
  snort3:
    image: snort3
    build:
      context: .
    network_mode: "host"
    volumes:
      # Map logs for offline mode
      - ./log/:/var/log/snort
      # Map configuration files and rules
      - ./etc/:/etc/snort/
      # Map pcaps
      - ./pcaps:/tmp
    # Specify the command:
    entrypoint:
      # Entrypoint
      ["snort",  "-c", "/etc/snort/snort.lua", "-l", "/var/log/snort", "-R", "/etc/snort/rules/snort.rules"]

    # Options appended to the entrypoint when calling docker-compose up
    command:
      # Offline mode
      ["--pcap-dir", "/tmp/"]
      #
      # Alternatively, capture contiuosly on ${CAPTURE_NIC} as defined in .env-file,
      #["-i", "${CAPTURE_NIC}"]
